# Generated by Django 5.0.6 on 2024-06-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("telegram", "0002_alter_telegramuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=128, verbose_name="ФИО разработчика"),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Начало рабочего дня"),
                ),
                ("end_time", models.DateTimeField(verbose_name="Конец рабочего дня")),
                (
                    "employer_status",
                    models.FloatField(verbose_name="Текущая занятость"),
                ),
                (
                    "tg_urls",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="telegram.telegramuser",
                        verbose_name="Ссылка на телеграм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разработчик",
                "verbose_name_plural": "Разработчики",
                "ordering": ["-user_name"],
            },
        ),
    ]
