# Generated by Django 5.0.6 on 2024-06-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="tg_urls",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Здесь должна быть ссылка на тг",
            ),
        ),
    ]
