# Generated by Django 5.0.6 on 2024-06-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0002_alter_employer_tg_urls"),
        ("telegram", "0004_telegramuser_selected_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employer",
            name="tg_urls",
        ),
        migrations.AddField(
            model_name="employer",
            name="tg_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="telegram.telegramuser",
                verbose_name="Ссылка на телеграм",
            ),
        ),
    ]
