# Generated by Django 5.0.6 on 2024-07-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0003_remove_employer_tg_urls_employer_tg_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="redmine_id",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="ID redmine"
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="redmine_url",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="URL redmine"
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="employer_status",
            field=models.FloatField(default=0, verbose_name="Текущая занятость"),
        ),
    ]
