# Generated by Django 5.0.6 on 2024-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0004_employer_redmine_id_employer_redmine_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Конец рабочего дня"
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало рабочего дня"
            ),
        ),
    ]
