# Generated by Django 5.0.6 on 2024-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0005_alter_employer_end_time_alter_employer_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="qrqode",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="qr",
                verbose_name="QR код",
            ),
        ),
    ]
