# Generated by Django 5.0.6 on 2024-07-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0006_employer_qrqode"),
        ("telegram", "0004_telegramuser_selected_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="tg_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redmine",
                to="telegram.telegramuser",
                verbose_name="Ссылка на телеграм",
            ),
        ),
    ]
