# Generated by Django 5.0.6 on 2024-06-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="Название задачи"),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Все задачи",
            },
        ),
        migrations.CreateModel(
            name="TaskData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=128, verbose_name="Статус выполнения задачи"
                    ),
                ),
                (
                    "priority",
                    models.CharField(max_length=128, verbose_name="Приоритет задачи"),
                ),
                (
                    "ready",
                    models.CharField(
                        max_length=128, verbose_name="Статус готовности задачи"
                    ),
                ),
                (
                    "time_manage",
                    models.IntegerField(verbose_name="Оценка временных затрат"),
                ),
                ("work_manage", models.IntegerField(verbose_name="Трудозатраты")),
                (
                    "initiator",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=128,
                        null=True,
                        verbose_name="От кого был создан запрос",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(max_length=128, verbose_name="Тип задачи"),
                ),
                (
                    "project_name",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_name",
                        to="task.project",
                        verbose_name="Название задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текущая задача",
                "verbose_name_plural": "Список задач",
                "ordering": ["-project_name"],
            },
        ),
    ]
