# Generated by Django 5.0.6 on 2024-06-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты"},
        ),
        migrations.AlterField(
            model_name="taskdata",
            name="project_name",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_name",
                to="task.project",
                verbose_name="Название проекта",
            ),
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Время начала работы"),
                ),
                (
                    "end_time",
                    models.DateTimeField(verbose_name="Время окончания работы"),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=2048,
                        null=True,
                        verbose_name="Комментарий разработчика",
                    ),
                ),
                (
                    "ready_status",
                    models.CharField(max_length=128, verbose_name="Event - статус"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_name",
                        to="task.taskdata",
                        verbose_name="Название задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["start_time"],
            },
        ),
    ]
