# Generated by Django 5.0.6 on 2024-06-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_project_options_alter_taskdata_project_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время окончания работы"
            ),
        ),
    ]
