# Generated by Django 5.0.6 on 2024-06-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_events_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="task_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_name",
                to="task.taskdata",
                verbose_name="Задача",
            ),
        ),
    ]
