# Generated by Django 5.0.6 on 2024-06-24 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_events_task_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-project_name"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AlterModelOptions(
            name="taskdata",
            options={
                "ordering": ["-task_number"],
                "verbose_name": "Текущая задача",
                "verbose_name_plural": "Список задач",
            },
        ),
        migrations.RemoveField(
            model_name="taskdata",
            name="project_name",
        ),
        migrations.AddField(
            model_name="taskdata",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="task.project",
                verbose_name="Название проекта",
            ),
        ),
        migrations.AddField(
            model_name="taskdata",
            name="task_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Номер задачи"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=255, verbose_name="Название проекта"),
        ),
        migrations.AlterField(
            model_name="taskdata",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Новая"),
                    ("2", "В работе"),
                    ("3", "Обратная связь"),
                    ("4", "Решена"),
                    ("5", "Закрыта"),
                    ("6", "Пауза"),
                    ("7", "Отклонена"),
                ],
                max_length=1,
                null=True,
                verbose_name="Статус выполнения задачи",
            ),
        ),
    ]
