# Generated by Django 5.0.6 on 2024-06-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_alter_project_options_alter_taskdata_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="ready_status",
        ),
        migrations.AddField(
            model_name="events",
            name="event_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Проектирование"),
                    ("2", "Разработка"),
                    ("3", "Тестирование"),
                    ("4", "Изучение"),
                    ("5", "Оформление"),
                ],
                max_length=1,
                null=True,
                verbose_name="Event - статус",
            ),
        ),
        migrations.AlterField(
            model_name="taskdata",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Низкий"),
                    ("2", "Нормальный"),
                    ("3", "Высокий"),
                    ("4", "Немедленный"),
                    ("5", "Срочно"),
                ],
                max_length=1,
                null=True,
                verbose_name="Приоритет задачи",
            ),
        ),
        migrations.AlterField(
            model_name="taskdata",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="task.project",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="taskdata",
            name="ready",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "0%"),
                    ("2", "10%"),
                    ("3", "20%"),
                    ("4", "30%"),
                    ("5", "40%"),
                    ("6", "50%"),
                    ("7", "60"),
                    ("8", "70%"),
                    ("9", "80%"),
                    ("10", "90%"),
                    ("11", "100%"),
                ],
                max_length=2,
                null=True,
                verbose_name="Статус готовности задачи",
            ),
        ),
        migrations.AlterField(
            model_name="taskdata",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Анализ"),
                    ("2", "Доработка"),
                    ("3", "Задание разработчику"),
                    ("4", "Изучение"),
                    ("5", "Консультация"),
                    ("6", "Ошибка"),
                    ("7", "Ошибка ПО"),
                    ("8", "Ошибка пользователя"),
                    ("9", "Поддержка"),
                    ("10", "ПО Настройка"),
                    ("11", "ПО Установка"),
                    ("12", "Разработка"),
                    ("13", "Концепт"),
                    ("14", "Совещание"),
                    ("15", "Формирование ТЗ"),
                    ("16", "Внедрение"),
                ],
                max_length=2,
                null=True,
                verbose_name="Тип задачи",
            ),
        ),
    ]
