# Generated by Django 5.0.6 on 2024-06-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_remove_events_ready_status_events_event_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdata",
            name="task_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название задачи"
            ),
        ),
    ]
