# Generated by Django 5.0.6 on 2024-06-24 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0001_initial"),
        ("task", "0007_taskdata_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Разработчик",
                to="employers.employer",
                verbose_name="Работник",
            ),
        ),
    ]
