# Generated by Django 5.0.6 on 2024-07-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_events_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="redmine_id",
            field=models.IntegerField(
                null=True, unique=True, verbose_name="ID проекта в redmine"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="redmine_url",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Ссылка на проект"
            ),
        ),
    ]
