# Generated by Django 5.0.6 on 2024-07-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0009_project_redmine_id_project_redmine_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название проекта"),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["-name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="unique_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="task.uniqueproject",
            ),
        ),
    ]
