# Generated by Django 5.0.6 on 2024-07-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0010_uniqueproject_project_unique_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uniqueproject",
            options={
                "ordering": ["-name"],
                "verbose_name": "Уникальный проект",
                "verbose_name_plural": "Уникальные проекты",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="unique_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="porjects",
                to="task.uniqueproject",
            ),
        ),
    ]
