# Generated by Django 5.0.6 on 2024-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0011_alter_uniqueproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniqueproject",
            name="fk_counter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Количество проектов"
            ),
        ),
    ]
