# Generated by Django 5.0.6 on 2024-06-25 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_alter_telegramuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TGBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название бота"),
                ),
                ("token", models.CharField(max_length=255, verbose_name="Токен бота")),
            ],
            options={
                "verbose_name": "Бот",
                "verbose_name_plural": "Боты",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="bot",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="telegram.tgbot",
            ),
        ),
    ]
