# Generated by Django 5.0.6 on 2024-06-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TextData", "0001_initial"),
        ("telegram", "0003_tgbot_telegramuser_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="selected_language",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="users",
                to="TextData.language",
                verbose_name="Выбранный язык",
            ),
        ),
    ]
